package com.thewinterframework.configurate.config;

import com.google.auto.service.AutoService;
import com.thewinterframework.configurate.module.ConfigurateModule;
import com.thewinterframework.processor.context.ProcessorContext;
import com.thewinterframework.processor.handler.WinterAnnotationProcessor;
import com.thewinterframework.processor.template.TemplateBuilder;

import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import java.lang.annotation.Annotation;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * An annotation processor that generates a module for all classes annotated with {@link Configurate}.
 */
@AutoService(WinterAnnotationProcessor.class)
public class ConfigurateAnnotationProcessor implements WinterAnnotationProcessor {

    private static final Pattern ELEMENT_PATTERN = Pattern.compile("(?:<el>)([\\s\\S]*?)(?:<\\/el>)");

    @Override
    public Set<Class<? extends Annotation>> getSupportedAnnotations() {
        return Set.of(Configurate.class);
    }

    @Override
    public void onRoundStart(final ProcessorContext ctx) {
        ctx.wireModule(ConfigurateModule.class);
    }

    @Override
    public void handle(final TypeElement annotation, final Set<? extends Element> elements, final ProcessorContext ctx) {
        final var validElements = elements.stream()
                .filter(e -> e.getKind() == ElementKind.CLASS || e.getKind() == ElementKind.RECORD)
                .collect(Collectors.toSet());

        if (validElements.isEmpty()) {
            return;
        }

        final var pkg = getModulePackage(ctx);
        final var className = "ConfigurationsModule";
        final var fullClassName = pkg + "." + className;

        TemplateBuilder.fromResource("generated/AutoGeneratedConfigurateModule.java")
                .placeholder("PACKAGE_NAME", pkg)
                .placeholder("CLASS_NAME", className)
                .custom(content -> {
                    final var matcher = ELEMENT_PATTERN.matcher(content);
                    final var result = new StringBuilder();
                    var lastEnd = 0;

                    while (matcher.find()) {
                        result.append(content, lastEnd, matcher.start());

                        final var block = matcher.group(1);
                        final var builder = new StringBuilder();

                        final var alreadyWritten = new HashSet<String>();

                        for (final var element : validElements) {
                            final var configAnnotation = element.getAnnotation(Configurate.class);
                            if (configAnnotation == null) continue;

                            final var fileName = configAnnotation.value();
                            if (!alreadyWritten.add(fileName)) continue;

                            builder.append(block
                                    .replace("<CONFIG_NAME>", fileName)
                                    .replace("<CONFIG_OBJECT>", element.toString())
                            ).append(System.lineSeparator());
                        }

                        result.append(builder);
                        lastEnd = matcher.end();
                    }
                    result.append(content.substring(lastEnd));
                    return result.toString();
                })
                .write(ctx, fullClassName);

        ctx.wireModule(getModulePackage(ctx) + ".ConfigurationsModule");
    }

    public String getModulePackage(final ProcessorContext context) {
        return context.getWinterModulePackageString() + ".autogenerated_winter_config_module";
    }
}